dbConnectionString = "host=localhost port=5432 user=aske dbname=ogmios-datum-cache"

server.port = 9999
server.controlApiToken = "usr:pwd"

ogmios.address = "127.0.0.1"
ogmios.port = 1337

blockFetcher.autoStart = true
blockFetcher.startFromLast = true
blockFetcher.firstBlock.slot = 44366242
blockFetcher.firstBlock.id = "d2a4249fe3d0607535daa26caf12a38da2233586bc51e79ed0b3a36170471bf5"
blockFetcher.filter = '''
{
    "all": [
        {
            "hash": "foobar"
        },
        {
            "any": [
                { "address": "addr_abc" },
                { "address": "addr_xyz" }
            ]
        }
    ]
}
'''
